"""
Hallar DSS — Complete Justification Data & Improved Calculator

Generated by Claude for the redesigned Scenarios page.
Every number has a written Icelandic justification.

Contents:
1. SCENARIO_FACTOR_JUSTIFICATIONS — 84 justification texts (12 scenarios × 7 factors)
2. RISK_CONFIDENCE_TIERS — confidence rating for each of 33 risks
3. RISK_BASE_JUSTIFICATIONS — why each base probability is what it is
4. calculate_risk_logistic() — improved probability calculation
5. validate_all() — comprehensive validation
"""

from __future__ import annotations
import math
from typing import Dict, Tuple, List, Optional
from dataclasses import dataclass


# ═══════════════════════════════════════════════════════════════════
# 1. SCENARIO FACTOR JUSTIFICATIONS (Icelandic)
# ═══════════════════════════════════════════════════════════════════
#
# Structure: SCENARIO_FACTOR_JUSTIFICATIONS[scenario_id][factor_id] = text
#
# Each justification answers: "Why does THIS scenario get THIS score?"
# Written for lawyers and decision-makers in plain Icelandic.
# ═══════════════════════════════════════════════════════════════════

SCENARIO_FACTOR_JUSTIFICATIONS: Dict[str, Dict[str, str]] = {

    # ─── S1: Hefðbundin leið borgar ────────────────────────────
    "S1": {
        "F1": (
            "**Einkunn: 2 (Tveir aðilar)**\n\n"
            "Borgin er eini eigandinn en þarf að samhæfa við marga verktaka og "
            "ráðgjafa í gegnum samningaferli. Raunveruleg ákvarðanataka er hjá "
            "borginni (einn eigandi) en skipulagsleg flækja er meiri en ef um "
            "einn einkaframkvæmdaraðila væri að ræða, vegna nefndakerfa og "
            "pólitísks ferlis. Einkunn 2 endurspeglar þetta."
        ),
        "F2": (
            "**Einkunn: 2 (Frekar veikir verktakar)**\n\n"
            "Borgin notar opinber útboð þar sem lægsta boð ræður oft för. "
            "Þetta laðar ekki endilega að sterkustu verktakana — þeir kjósa "
            "frekar einkaverkefni með betri framlegð. Verktakar eru valdir á "
            "verði, ekki á getu. Reynslan af opinberum framkvæmdum á Íslandi "
            "sýnir að þetta leiðir oft til veikari verktaka."
        ),
        "F3": (
            "**Einkunn: 3 (Miðlungs fjármagnsþol)**\n\n"
            "Borgin fjármagnar í gegnum fjárlög og hugsanlega skuldabréf. "
            "Þetta er hvorki bankalán (óþolinmótt) né lífeyrissjóðsfé "
            "(þolinmótt). Borgin þolir tafir betur en banki en er háð "
            "fjárlagaferli og pólitískum ákvörðunum um fjárveitingar."
        ),
        "F4": (
            "**Einkunn: 3 (Miðlungs samþætting)**\n\n"
            "Borgin skipuleggur verkefnið og hefur yfirumsjón með framkvæmdum "
            "í gegnum eigin innkaupa- og eftirlitsferli. Þó verktaki sé valinn í "
            "útboði kemur hann inn á skipulagsstig ef borgin beitir sér. Borgin "
            "stýrir bæði skipulagsákvörðunum og framkvæmdaeftirliti, sem er meiri "
            "samþætting en hefðbundið design-bid-build en ekki full samþætting."
        ),
        "F5": (
            "**Einkunn: 2 (Lítil fagleg verkefnastjórnun)**\n\n"
            "Borgaframkvæmdir eru yfirleitt stýrt af nefndum og deildum "
            "borgarinnar, ekki af sérstökum verkefnastjóra með umboð og hvata. "
            "Reynsla af opinberum framkvæmdum á Íslandi sýnir að "
            "nefndarstjórnun er hægari og minna markviss en fagleg "
            "verkefnastjórnun með skýru umboði."
        ),
        "F6": (
            "**Einkunn: 5 (Borg er aðaleigandi)**\n\n"
            "Borgin á og stýrir verkefninu beint. Hún getur þrýst á Veitur "
            "ohf. (sem borgin á), samræmt innviðaáætlanir, og tryggt að "
            "félagsleg markmið náist. Þetta er hæsta mögulega einkunn á F6."
        ),
        "F7": (
            "**Einkunn: 5 (Hámarks samningsstaða)**\n\n"
            "Borgin er bæði skipulagsyfirvald og eigandi. Hún setur "
            "skilyrði í útboðum, samningum og deiliskipulagi. Borgin "
            "stýrir verkefninu beint og þarf ekki að semja við eigendur — "
            "hún er eigandinn. Þetta er hámarks framfylgdugeta."
        ),
    },

    # ─── S2: Lífeyrissjóður + Verkefnastjóri ─────────────────
    "S2": {
        "F1": (
            "**Einkunn: 2 (Tveir aðilar)**\n\n"
            "Lífeyrissjóður er aðaleigandi og ræður verkefnastjóra sem "
            "launþega/verktaka (ekki meðeiganda). Ákvarðanataka er hjá "
            "sjóðnum, verkefnastjóri framfylgir. Einfalt skipulag."
        ),
        "F2": (
            "**Einkunn: 3 (Miðlungs verktakastyrkur)**\n\n"
            "Verktaki er valinn í útboði af verkefnastjóra. Enginn "
            "eignarhluti skapar hvata til sterkra verktaka en fagleg "
            "verkefnastjórnun tryggir ágætt val. Verktaki er samnings-"
            "bundinn en ekki eigandi."
        ),
        "F3": (
            "**Einkunn: 5 (Mjög þolinmótt fjármagn)**\n\n"
            "Lífeyrissjóður fjármagnar eingöngu með eigin fé. Engir "
            "bankavextir, engar afborganir. Sjóðurinn þolir 5-10 ára "
            "fjárfestingartíma og sveiflur á markaði. Þetta er þolinmóðasta "
            "fjármagnið sem hægt er að fá."
        ),
        "F4": (
            "**Einkunn: 3 (Miðlungs samþætting)**\n\n"
            "Verkefnastjóri stýrir bæði skipulagi og vali á verktaka, sem "
            "tryggir eitthvert samráð. En verktaki kemur inn eftir skipulag "
            "og er ekki hönnunaraðili. Betra en S1 vegna faglegs "
            "verkefnastjóra en ekki full samþætting."
        ),
        "F5": (
            "**Einkunn: 4 (Góð fagleg stjórnun)**\n\n"
            "Faglegur verkefnastjóri er ráðinn sérstaklega til að stýra "
            "verkefninu. Hann hefur skýrt umboð frá lífeyrissjóði. Ekki 5 "
            "vegna þess að verkefnastjóri er launþegi, ekki meðeigandi — "
            "minni persónulegur hvati til árangurs."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Borgin selur lóð og setur skilyrði í kaupsamningi en er ekki "
            "meðeigandi. Getur ekki þrýst á eigendur eða Veitur sem eigandi."
        ),
        "F7": (
            "**Einkunn: 3 (Miðlungs samningsstaða)**\n\n"
            "Borgin hefur skilyrði í lóðarsamningi en engin eignaráhrif. "
            "Samningsstaðan er hefðbundin og byggir á hefðbundnum "
            "lóðarskilmálum."
        ),
    },

    # ─── S3: Lífeyrissjóður + Verkefnastjóri sem meðeigandi ──
    "S3": {
        "F1": (
            "**Einkunn: 2 (Tveir eigendur)**\n\n"
            "Lífeyrissjóður og verkefnastjóri deila eignarhaldi. Tveir "
            "aðilar í ákvarðanatöku — einfalt skipulag."
        ),
        "F2": (
            "**Einkunn: 3 (Miðlungs verktakastyrkur)**\n\n"
            "Svipað og S2 — verktaki valinn í útboði. Verkefnastjóri sem "
            "meðeigandi getur þó haft betri samningsstöðu við verktaka vegna "
            "langtímaálags. Enn sem áður er verktaki ekki eigandi."
        ),
        "F3": (
            "**Einkunn: 5 (Mjög þolinmótt fjármagn)**\n\n"
            "Sama og S2 — lífeyrissjóður fjármagnar. Framlag verkefnastjóra "
            "er lítið hlutfall heildarfjármagns."
        ),
        "F4": (
            "**Einkunn: 3 (Miðlungs samþætting)**\n\n"
            "Sama og S2 — verkefnastjóri stýrir en verktaki kemur inn seinna."
        ),
        "F5": (
            "**Einkunn: 5 (Sterkasta fagleg stjórnun)**\n\n"
            "Verkefnastjóri er meðeigandi og hefur fjárhagslega hagsmuni "
            "af árangri. Þetta er nákvæmlega það sem skalinn skilgreinir "
            "sem 5: 'Faglegur stjóri með eignarhlut'. Meðeign skapar "
            "hámarks persónulegan hvata — verkefnastjóri tapar eigin fé "
            "ef verkefnið bregst. Þetta er sterkasta form persónulegrar "
            "ábyrgðar verkefnastjóra, þó stofnanastyrkur sé minni en "
            "hjá þróunarfyrirtæki (sjá S5 sem nær 5 á annan hátt)."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Lífeyrissjóður og verkefnastjóri eiga verkefnið saman. Borgin "
            "selur lóð og setur skilyrði í kaupsamningi en situr ekki í "
            "stjórn félagsins og getur ekki beint þrýst á framkvæmdir."
        ),
        "F7": (
            "**Einkunn: 3 (Miðlungs samningsstaða)**\n\n"
            "Borgin setur hefðbundin lóðarskilyrði í kaupsamningi. Engin "
            "eignarstaða styrkir samningsstöðuna. Verkefnastjóri sem meðeigandi "
            "breytir ekki samningsstöðu borgarinnar — hún er enn utanaðkomandi."
        ),
    },

    # ─── S4: Lífeyrissjóður + Aðalverktaki sem meðeigandi ────
    "S4": {
        "F1": (
            "**Einkunn: 2 (Tveir eigendur)**\n\n"
            "Lífeyrissjóður og aðalverktaki eru meðeigendur. Tveir aðilar "
            "í ákvarðanatöku. Einfalt og skilvirkt skipulag."
        ),
        "F2": (
            "**Einkunn: 5 (Mjög sterkur verktaki)**\n\n"
            "Aðalverktaki er meðeigandi sem krefst þess að hann sé stór "
            "og fjárhagslega sterkur — hann leggur eigið fé í verkefnið. "
            "Aðeins sterkustu verktakar landsins (Ístak, Miðás, Íbúðir) "
            "geta tekið þessa áhættu. Eignarhluti skapar einnig hvata "
            "til að ljúka verkefni — verktaki tapar ef hann bregst."
        ),
        "F3": (
            "**Einkunn: 5 (Mjög þolinmótt fjármagn)**\n\n"
            "Lífeyrissjóður fjármagnar meginhluta. Aðalverktaki leggur til "
            "eigið fé (ekki bankalán) sem hluta af eignarframlagi sínu. "
            "Engir bankavextir, engar afborganir. "
            "Fjármagnið þolir langan fjárfestingartíma og markaðssveiflur."
        ),
        "F4": (
            "**Einkunn: 5 (Full samþætting)**\n\n"
            "Aðalverktaki sem er meðeigandi leiðir BÆÐI deiliskipulagsgerð "
            "OG framkvæmdir. Hönnun tekur mið af byggjanleika frá degi eitt. "
            "Engar breytingabeiðnir — sami aðili skipuleggur og byggir. "
            "Þetta er sterkasta samþætting sem hægt er að ná."
        ),
        "F5": (
            "**Einkunn: 4 (Góð fagleg stjórnun)**\n\n"
            "Verkefnastjóri ráðinn af félaginu. Aðalverktaki hefur einnig "
            "innbyggða hvata vegna eignarhluta. Ekki 5 vegna þess að "
            "verkefnastjóri er ekki sjálfur eigandi (ólíkt S3)."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Borgin selur lóð og setur skilyrði í kaupsamningi en situr "
            "ekki við eigendaborðið. Getur ekki þrýst á Veitur sem eigandi. "
            "**Þetta er helsti veikleiki S4.**"
        ),
        "F7": (
            "**Einkunn: 3 (Miðlungs samningsstaða)**\n\n"
            "Borgin hefur hefðbundin lóðarskilyrði en ekkert umfram það. "
            "Sterkari en S9 (engin skilyrði) en veikari en S10/S11 þar "
            "sem borgin er eigandi."
        ),
    },

    # ─── S5: Lífeyrissjóðir gegnum Summa/Reitir ──────────────
    "S5": {
        "F1": (
            "**Einkunn: 2 (Einfalt skipulag)**\n\n"
            "Lífeyrissjóðir fjárfesta í gegnum þróunarfyrirtæki (t.d. Summa "
            "eða Reitir) og fela því ákvarðanatöku. Sjóðirnir sitja á stjórn "
            "en skipta sér ekki af daglegum ákvörðunum. Þróunarfyrirtækið er "
            "eini raunverulegi ákvarðanaaðilinn í framkvæmdum — svipað og S2 "
            "þar sem lífeyrissjóður ræður verkefnastjóra."
        ),
        "F2": (
            "**Einkunn: 4 (Sterkur verktaki)**\n\n"
            "Summa/Reitir velja reynda verktaka og hafa sögulega unnið með "
            "stórum verktökum. Verktaki er ekki eigandi en fagfélagið tryggir "
            "ágætan gæðastaðal. Ekki 5 vegna þess að verktaki er ekki "
            "eigandi og hefur veikari hvata en í S4."
        ),
        "F3": (
            "**Einkunn: 5 (Mjög þolinmótt fjármagn)**\n\n"
            "Allt fjármagn kemur frá lífeyrissjóðum. Sama rök og S4."
        ),
        "F4": (
            "**Einkunn: 4 (Góð samþætting)**\n\n"
            "Summa/Reitir hafa reynslu af samþættum verkefnum þar sem "
            "verktaki kemur snemma inn. Ekki 5 vegna þess að félagið er "
            "millistig milli sjóða og verktaka sem getur hægt á."
        ),
        "F5": (
            "**Einkunn: 5 (Sterkasta fagleg stjórnun)**\n\n"
            "Summa/Reitir eru fasteignaþróunarfyrirtæki sem eru meðeigendur "
            "verkefnisins. Þau hafa bæði stofnanalegan styrk (kerfi, starfsfólk, "
            "reynslu af mörgum stórum verkefnum) OG eignarhlut sem skapar "
            "fjárhagslegan hvata. Þetta er sterkasta form faglegrar stjórnunar: "
            "dýpt stofnunar ásamt persónulegum hagsmunum af árangri."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Lífeyrissjóðir fjárfesta í gegnum þróunarfyrirtæki. Borgin er "
            "ekki meðeigandi og situr ekki í stjórn. Hún getur ekki þrýst á "
            "Veitur eða samræmt innviðaáætlanir sem eigandi."
        ),
        "F7": (
            "**Einkunn: 3 (Miðlungs samningsstaða)**\n\n"
            "Borgin setur hefðbundin lóðarskilyrði. Þróunarfyrirtækið (Summa/"
            "Reitir) er millistigið — borgin semur við það, ekki beint við "
            "verktaka. Samningsstaðan er hefðbundin og ekkert eignarhlut styrkir hana."
        ),
    },

    # ─── S6: Lífeyrissjóður byggir innviði, selur byggingarrétt ─
    "S6": {
        "F1": (
            "**Einkunn: 3 (Nokkrir aðilar)**\n\n"
            "Í fyrsta áfanga er lífeyrissjóður einn eigandi innviða. Í öðrum "
            "áfanga koma margir kaupendur byggingarréttar — sem skapar "
            "samhæfingaráhættu. Meðaltal tveggja áfanga gefur 3."
        ),
        "F2": (
            "**Einkunn: 2 (Frekar veikir verktakar)**\n\n"
            "Byggingarréttur seldur í opnu útboði — líklegt er að blöndun "
            "verktaka komi, sumir sterkir, aðrir veikari. Engin trygging "
            "á sterkum verktökum."
        ),
        "F3": (
            "**Einkunn: 3 (Miðlungs fjármagnsþol)**\n\n"
            "Lífeyrissjóður fjármagnar innviði (áfangi 1) með þolinmóðu fé. "
            "En kaupendur byggingarréttar fjármagna sjálfir byggingaráfanga — "
            "líklega með bankalánum. Þar sem flest áhætta er í byggingaráfanga "
            "og sú fjármögnun er óþolinmóð, er heildareinkunn lægri en 4."
        ),
        "F4": (
            "**Einkunn: 1 (Engin samþætting)**\n\n"
            "Algjör aðskilnaður: lífeyrissjóður skipuleggur og byggir "
            "innviði, síðan kaupa verktakar byggingarrétt og byggja "
            "samkvæmt eigin hönnun. Breytingabeiðnir frá kaupendum "
            "byggingarréttar eru nánast óhjákvæmilegar. **Þetta er "
            "veikasta samþættingin af öllum sviðsmyndum.**"
        ),
        "F5": (
            "**Einkunn: 2 (Lítil heildarstjórnun)**\n\n"
            "Lífeyrissjóður stýrir innviðaáfanga af nokkurri fagmennsku en "
            "eftir sölu byggingarréttar er enginn sem samhæfir heildarverkefnið. "
            "Byggingaráfangi er stýrt af hverjum kaupanda fyrir sig — engin "
            "samræmd verkefnastjórnun á milli þeirra."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Borgin er ekki eigandi á neinum áfanga. Lífeyrissjóður á innviðaáfanga "
            "og kaupendur byggingarréttar eiga sinn hluta. Borgin hefur enga "
            "beina aðkomu að framkvæmdum eftir sölu lóðar."
        ),
        "F7": (
            "**Einkunn: 2 (Lítil samningsstaða)**\n\n"
            "Borgin setur lóðarskilyrði en eftir sölu byggingarréttar er "
            "erfitt að þrýsta á einstakar lóðir. Veikari en hefðbundin "
            "lóðarskilyrði vegna þess að samskiptin eru enn fjarlægari."
        ),
    },

    # ─── S7: Bankafjármögnun + 2-3 stórir verktakar ──────────
    "S7": {
        "F1": (
            "**Einkunn: 3 (Þrír aðilar)**\n\n"
            "2-3 verktakar eru meðeigendur. Þrír eða fleiri ákvarðanaaðilar "
            "sem þurfa samþykki. Bæði samkeppni og samstarf á milli "
            "verktaka skapar flókið afl."
        ),
        "F2": (
            "**Einkunn: 4 (Sterkir verktakar)**\n\n"
            "Stórir verktakar sem geta lagt til eigið fé í verkefnið eru "
            "fjárhagslega sterkir. 2-3 stórir verktakar dreifa áhættu. "
            "Ekki 5 vegna þess að enginn einn verktaki ber heildarábyrgð."
        ),
        "F3": (
            "**Einkunn: 1 (Mjög óþolinmótt fjármagn)**\n\n"
            "Bankafjármögnun þýðir vexti, afborganir og skilyrði sem krefjast "
            "stöðugs sjóðstreymis. Ef markaður hrynur eða tafir verða, "
            "getur banki krafist endurgreiðslu eða tekið yfir eignir. "
            "**Þetta er hættulegasta fjármögnunin.**"
        ),
        "F4": (
            "**Einkunn: 4 (Góð samþætting)**\n\n"
            "Verktakar eru eigendur og leiða framkvæmdir. Hönnun og bygging "
            "samþætt. Svipað og S4 en dreift á fleiri aðila."
        ),
        "F5": (
            "**Einkunn: 3 (Miðlungs stjórnun)**\n\n"
            "Verkefnastjóri ráðinn en þarf að samhæfa á milli 2-3 verktaka. "
            "Enginn einn verktaki hefur fullt umboð. Miðlungs árangur."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Verktakar og banki eiga verkefnið. Borgin er ekki meðeigandi og "
            "situr ekki við ákvarðanaborðið. Ef markaður bregst er banki "
            "aðaláhrifavaldur, ekki borgin."
        ),
        "F7": (
            "**Einkunn: 2 (Lítil samningsstaða)**\n\n"
            "Borgin hefur lóðarskilyrði en veikt vald. Ef verktakar og banki "
            "taka yfir verkefnið hefur borgin takmarkaðar leiðir."
        ),
    },

    # ─── S8: Bankafjármögnun + 1 stór verktaki ───────────────
    "S8": {
        "F1": (
            "**Einkunn: 1 (Einn eigandi)**\n\n"
            "Einn stór verktaki er eigandi. Bankinn er lánveitandi, ekki "
            "eigandi. Allar ákvarðanir eru hjá einum aðila — mjög einfalt."
        ),
        "F2": (
            "**Einkunn: 4 (Sterkur verktaki)**\n\n"
            "Einn stór verktaki sem getur fengið bankafjármögnun er "
            "fjárhagslega sterkur. Ekki 5 vegna þess að einbilunaráhætta "
            "er til staðar — ef þessi eini verktaki lendir í vandræðum "
            "er engin varaáætlun."
        ),
        "F3": (
            "**Einkunn: 1 (Mjög óþolinmótt fjármagn)**\n\n"
            "Sama og S7 — bankafjármögnun er óþolinmóð. Verri en S7 vegna "
            "þess að einn verktaki ber alla áhættuna á bönkum."
        ),
        "F4": (
            "**Einkunn: 5 (Full samþætting)**\n\n"
            "Einn verktaki skipuleggur og byggir — fullkomin samþætting. "
            "Sama og S4 í þessu tilliti."
        ),
        "F5": (
            "**Einkunn: 4 (Góð stjórnun)**\n\n"
            "Stór verktaki hefur innbyggða verkefnastjórnun. Bankinn krefst "
            "einnig reglubundinna skýrslna og eftirlits. Ekki 5 vegna "
            "þess að engin utanaðkomandi gæðatrygging er til staðar."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Einn stór verktaki á verkefnið með bankafjármögnun. Borgin er "
            "ekki meðeigandi. Ef verktaki lendir í fjárhagsvandræðum tekur "
            "banki yfir og borgin hefur engin eignaráhrif."
        ),
        "F7": (
            "**Einkunn: 2 (Lítil samningsstaða)**\n\n"
            "Borgin hefur lóðarskilyrði en ef verktaki lendir í vandræðum "
            "tekur banki yfir og borgarinnar skilyrði verða erfiðari "
            "að framfylgja."
        ),
    },

    # ─── S9: Margir smáir verktakar ──────────────────────────
    "S9": {
        "F1": (
            "**Einkunn: 5 (Mjög margir eigendur)**\n\n"
            "Margar lóðir seldar mörgum smáum verktökum. Enginn einn aðili "
            "ber heildarábyrgð. Þetta er 'Úlfarsárdalur aftur' — enginn "
            "samhæfir og allir bera aðeins ábyrgð á sinni lóð. "
            "**Hæsta flækjustig.**"
        ),
        "F2": (
            "**Einkunn: 1 (Veikir verktakar)**\n\n"
            "Smáir verktakar hafa takmarkað eigið fé, takmarkaða reynslu "
            "af stórum verkefnum, og eru viðkvæmir fyrir fjárhagsvandræðum. "
            "Margir smáir verktakar = há hætta á að einhver lendi í "
            "vandræðum. **Veikasta staðan.**"
        ),
        "F3": (
            "**Einkunn: 1 (Mjög óþolinmótt fjármagn)**\n\n"
            "Smáir verktakar reiða sig nánast algjörlega á bankalán. "
            "Lítið eigið fé, háir vextir, stuttir lánatímar. Ef tafir verða "
            "eða markaður hrynur geta bankarnir krafist endurgreiðslu. "
            "Þetta er jafn óþolinmótt og S7/S8 en með veikari verktaka."
        ),
        "F4": (
            "**Einkunn: 1 (Engin samþætting)**\n\n"
            "Hver verktaki skipuleggur og byggir sína lóð sjálfstætt. "
            "Engin samhæfing á hönnun eða framkvæmdum á milli lóða. "
            "**Engin samþætting.**"
        ),
        "F5": (
            "**Einkunn: 1 (Engin fagleg stjórnun)**\n\n"
            "Enginn heildarverkefnastjóri. Hver verktaki stýrir sjálfur. "
            "Engin samhæfing, engin gæðatrygging, engin heildaráætlun. "
            "**Verst mögulega.**"
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Borgin selur lóðir til smáverktaka og er ekki eigandi neins hluta "
            "verkefnisins. Hún getur ekki þrýst á neinn verktaka sem eigandi "
            "og hefur enga beina aðkomu að framkvæmdum."
        ),
        "F7": (
            "**Einkunn: 1 (Engin samningsstaða)**\n\n"
            "Borgin selur lóðir beint til smáverktaka. Eftir sölu hefur "
            "borgin nánast engin áhrif. Ef verktaki stendur ekki við "
            "skuldbindingar er erfitt að bregðast við. "
            "**Veikasta samningsstaðan.**"
        ),
    },

    # ─── S10: Borg + Lífeyrissjóðir sem meðeigendur ──────────
    "S10": {
        "F1": (
            "**Einkunn: 3 (Flókin ákvarðanataka)**\n\n"
            "Tveir eigendur: borgin og lífeyrissjóður. En þessir tveir aðilar "
            "hafa gjörólíka ákvarðanaferla — borgin gengur í gegnum nefndir, "
            "borgarráð og borgarstjórn (opinbert, pólitískt), en sjóðurinn "
            "gengur í gegnum fjárfestinganefnd og stjórn (einkamál, fjárhagslegt). "
            "Ólíkir tímarammar og menning gera samvinnu flóknari en ef um "
            "tvo einkaraðila væri að ræða."
        ),
        "F2": (
            "**Einkunn: 3 (Miðlungs verktakastyrkur)**\n\n"
            "Verktaki valinn í útboði af félaginu. Borgin og sjóðurinn "
            "velja saman — geta valið sterkan verktaka en hann er ekki "
            "eigandi og hefur þar af leiðandi veikari hvata."
        ),
        "F3": (
            "**Einkunn: 4 (Þolinmótt fjármagn)**\n\n"
            "Lífeyrissjóður leggur til meginhluta fjármagns. Borgin leggur "
            "til lóð (ekki reiðufé). Fjármagnið er aðallega þolinmótt en "
            "borgin hefur pólitískar tímaáætlanir sem geta skapað þrýsting. "
            "Því 4, ekki 5."
        ),
        "F4": (
            "**Einkunn: 3 (Miðlungs samþætting)**\n\n"
            "Félagið stýrir skipulagi og velur verktaka. Miðlungs samþætting — "
            "betra en S1 (borg ein) en verra en S4 (verktaki eigandi og "
            "skipuleggjandi)."
        ),
        "F5": (
            "**Einkunn: 3 (Miðlungs stjórnun)**\n\n"
            "Verkefnastjóri ráðinn af félaginu. Borgin vill hafa áhrif á "
            "stýringu sem getur skapað togstreitu. Miðlungs faglegur styrkur."
        ),
        "F6": (
            "**Einkunn: 4 (Borg með stóran hlut)**\n\n"
            "Borgin er meðeigandi með verulegum hlut. Getur þrýst á Veitur, "
            "samræmt innviðaáætlanir, og tryggt félagsleg markmið. "
            "Ekki 5 vegna þess að lífeyrissjóður á meirihluta."
        ),
        "F7": (
            "**Einkunn: 4 (Sterk samningsstaða)**\n\n"
            "Borgin situr bæði við eigendaborðið og hefur skipulagsvald. "
            "Sterk staða til að framfylgja markmiðum."
        ),
    },

    # ─── S11: Borg + Lífeyrissjóðir + Aðalverktaki ───────────
    "S11": {
        "F1": (
            "**Einkunn: 4 (Mikil flækja í ákvarðanatöku)**\n\n"
            "Þrír meðeigendur með gjörólíka menningu og hvata: borgin "
            "(pólitísk, hæg, opinber ábyrgð), lífeyrissjóður (fjárhagsleg "
            "ávöxtun, þolinmæði), og aðalverktaki (framlegð, hraði, "
            "framkvæmdahagkvæmni). Allar stórar ákvarðanir krefjast samkomulags "
            "þriggja aðila sem hugsa á ólíkan hátt og starfa á ólíkum "
            "tímaramma. Flóknara en S5 (sjóðir fela þróunarfyrirtæki ákvörðun) "
            "og flóknara en S7 (verktakar með svipaða menningu)."
        ),
        "F2": (
            "**Einkunn: 5 (Mjög sterkur verktaki)**\n\n"
            "Sama og S4 — aðalverktaki sem meðeigandi krefst fjárhagslega "
            "sterks verktaka. Eignarhluti skapar sterkan hvata."
        ),
        "F3": (
            "**Einkunn: 4 (Þolinmótt fjármagn)**\n\n"
            "Lífeyrissjóður leggur til meginhluta. Borgin leggur til lóð. "
            "Aðallega þolinmótt en borgin hefur pólitískar tímaáætlanir "
            "(kosningaloforð, fjárlög) sem geta skapað tímaþrýsting á "
            "verkefnið. Þess vegna 4 en ekki 5."
        ),
        "F4": (
            "**Einkunn: 5 (Full samþætting)**\n\n"
            "Sama og S4 — aðalverktaki leiðir bæði skipulag og framkvæmdir."
        ),
        "F5": (
            "**Einkunn: 4 (Góð fagleg stjórnun)**\n\n"
            "Verkefnastjóri ráðinn af félaginu. Verktaki hefur innbyggðan "
            "hvata. Borgin bætir eftirliti. Ekki 5 vegna þess að þrír "
            "eigendur geta skapað togstreitu um stjórnun."
        ),
        "F6": (
            "**Einkunn: 3 (Borg með meðalhlut)**\n\n"
            "Borgin er meðeigandi með 20-30% hlut. Situr í stjórn, getur "
            "þrýst á Veitur, en á ekki meirihluta. Miðlungs áhrif."
        ),
        "F7": (
            "**Einkunn: 4 (Sterk samningsstaða)**\n\n"
            "Borgin er eigandi OG hefur skipulagsvald. Samningsskilyrði "
            "eru sterkari en í S4 vegna eignarstöðu. Ekki 5 vegna þess "
            "að borgin á ekki meirihluta."
        ),
    },

    # ─── S12: Lífeyrissjóður + Aðalverktaki (ekki eigandi) ───
    "S12": {
        "F1": (
            "**Einkunn: 2 (Tveir aðilar)**\n\n"
            "Lífeyrissjóður er eigandi. Aðalverktaki er samningsbundinn "
            "en ekki meðeigandi. Raunverulega einn eigandi í ákvarðanatöku "
            "en tveir aðilar í framkvæmd."
        ),
        "F2": (
            "**Einkunn: 4 (Sterkur verktaki)**\n\n"
            "Aðalverktaki er stór og reynslumikill — 'aðalverktaki' þýðir "
            "stórt fyrirtæki (t.d. Ístak, Eykt). Fjárhagslegur og "
            "rekstrarlegur styrkur er eiginleiki fyrirtækisins, ekki "
            "eignarhaldsskipulagsins. Munurinn á S4 og S12 er hvati "
            "(F4, samþætting), ekki geta (F2, styrkur). Verktakinn er jafn "
            "sterkur hvort sem hann er eigandi eða á samningi."
        ),
        "F3": (
            "**Einkunn: 5 (Mjög þolinmótt fjármagn)**\n\n"
            "Sama og S4 — lífeyrissjóður fjármagnar."
        ),
        "F4": (
            "**Einkunn: 4 (Góð samþætting)**\n\n"
            "Aðalverktaki á samningi hefur tæknilega byggingarþekkingu sem "
            "gerir honum kleift að veita byggjanleikaráðgjöf á skipulagsstigi, "
            "jafnvel án eignarhluta. Þetta er meiri samþætting en verkefnastjóri "
            "í S2 (sem skortir tæknilega byggingarþekkingu) en ekki full "
            "samþætting eins og S4 þar sem verktaki er meðeigandi og tekur "
            "þátt í öllum ákvörðunum frá degi eitt með fjárhagslega hvata."
        ),
        "F5": (
            "**Einkunn: 4 (Góð fagleg stjórnun)**\n\n"
            "Verkefnastjóri ráðinn af lífeyrissjóði. Aðalverktaki er "
            "faglegur en ekki eigandi. Svipað og S2 en sterkara vegna "
            "þess að verktaki er aðalverktaki, ekki almennur."
        ),
        "F6": (
            "**Einkunn: 1 (Borg ekki eigandi)**\n\n"
            "Lífeyrissjóður á verkefnið og ræður aðalverktaka á samningi. "
            "Borgin er ekki meðeigandi og situr ekki í stjórn. Munurinn á "
            "S4 og S12 er eignarstaðan — í S12 er borgin algjörlega utan."
        ),
        "F7": (
            "**Einkunn: 3 (Miðlungs samningsstaða)**\n\n"
            "Borgin setur hefðbundin lóðarskilyrði en hefur enga eignarstöðu "
            "til að styrkja samningsstöðuna. Svipað og önnur sjóðsdrifin "
            "verkefni þar sem borgin er utanaðkomandi."
        ),
    },
}


# ═══════════════════════════════════════════════════════════════════
# 2. RISK CONFIDENCE TIERS
# ═══════════════════════════════════════════════════════════════════

@dataclass
class RiskConfidence:
    tier: str          # "Hátt öryggi", "Miðlungs öryggi", "Lágt öryggi"
    tier_en: str       # For internal reference
    justification: str # Why this confidence level


RISK_CONFIDENCE: Dict[str, RiskConfidence] = {
    "R01": RiskConfidence("Miðlungs öryggi", "Medium",
        "Seinkun á deiliskipulagi er vel þekkt á Íslandi en tímalengd er mjög breytileg eftir aðstæðum."),
    "R02": RiskConfidence("Miðlungs öryggi", "Medium",
        "Kærur eru vel skjalfest ferli en líkur eru háðar staðsetningu og andstöðu."),
    "R03": RiskConfidence("Lágt öryggi", "Low",
        "Skipulag sem hentar ekki markaði er erfitt að spá — háð efnahagsþróun og eftirspurn."),
    "R04": RiskConfidence("Hátt öryggi", "High",
        "Breytingabeiðnir frá verktökum eru vel rannsökuð fyrirbæri í framkvæmdaiðnaði. "
        "Tengsl við samþættingu (F4) eru sterk og vel skjalfest."),
    "R05": RiskConfidence("Miðlungs öryggi", "Medium",
        "Umhverfismat er lagalegt ferli en tímalengd er breytileg."),
    "R06": RiskConfidence("Lágt öryggi", "Low",
        "Fornleifafundir eru óútreiknanlegar — háð staðsetningu og sögu svæðis."),
    "R08": RiskConfidence("Hátt öryggi", "High",
        "Kostnaðarauki innviða er vel skjalfest í íslenskum framkvæmdum. "
        "Gagnasafn Ríkisendurskoðunar sýnir 30–80% kostnaðarfrávik á opinberum verkefnum."),
    "R09": RiskConfidence("Miðlungs öryggi", "Medium",
        "Gallar í innviðum eru þekktir en erfitt að mæla á sama kvarða."),
    "R10": RiskConfidence("Hátt öryggi", "High",
        "Innviða- og veitutafir eru vel skjalfest í íslenskum byggingariðnaði. "
        "Veitur OR er þekktur flöskuháls sem bætist við almenna innviðaseinkun."),
    "R11": RiskConfidence("Hátt öryggi", "High",
        "Gjaldþrot verktaka er vel skjalfest á Íslandi — nokkur stór tilvik síðustu 15 ár. "
        "Tengsl við verktakastyrk (F2) eru bein og sterk."),
    "R12": RiskConfidence("Hátt öryggi", "High",
        "Byggingarkostnaður og efnisverð umfram áætlun er vel rannsökuð á alþjóðavísu og "
        "íslenskum gögnum. Ísland flytur inn stærstan hluta byggingarefnis og er viðkvæmt."),
    "R13": RiskConfidence("Hátt öryggi", "High",
        "Tafir á byggingum eru vel skjalfest í framkvæmdaiðnaði."),
    "R14": RiskConfidence("Miðlungs öryggi", "Medium",
        "Gæðavandamál í byggingum eru þekkt en erfitt að mæla á hlutlægan hátt."),
    "R15": RiskConfidence("Miðlungs öryggi", "Medium",
        "Skortur á fagfólki er sveiflukenndur og háður efnahagsástandi á Íslandi."),
    "R17": RiskConfidence("Hátt öryggi", "High",
        "Léleg samhæfing milli verktaka er vel rannsökuð í verkefnastjórnun. "
        "Tengsl við flækjustig ákvarðanatöku (F1) eru sterk og vel skjalfest."),
    "R18": RiskConfidence("Lágt öryggi", "Low",
        "Eftirspurnarsamdráttur er þjóðhagslegt fyrirbæri sem er erfitt að spá."),
    "R19": RiskConfidence("Lágt öryggi", "Low",
        "Verðlækkun á markaði er háð mörgum ytri þáttum."),
    "R20": RiskConfidence("Lágt öryggi", "Low",
        "Vaxtahækkanir eru háðar Seðlabankastefnu og alþjóðlegum þáttum."),
    "R22": RiskConfidence("Miðlungs öryggi", "Medium",
        "Fjármögnunarbrestur er háð bæði verkefnagæðum og almennu fjármálaástandi."),
    "R23": RiskConfidence("Miðlungs öryggi", "Medium",
        "Lífeyrissjóðir hafa sögulega haldið við skuldbindingum en geta breytt stefnu."),
    "R24": RiskConfidence("Lágt öryggi", "Low",
        "Stefnubreytingar borgarstjórnar eru pólitískt fyrirbæri sem er erfitt að spá."),
    "R25": RiskConfidence("Lágt öryggi", "Low",
        "Nýjar reglugerðir eru óútreiknanlegar — háðar lagabreytingum á Alþingi."),
    "R26": RiskConfidence("Lágt öryggi", "Low",
        "Andstaða almennings er háð mörgum félagslegum þáttum og erfitt að spá."),
    "R27": RiskConfidence("Hátt öryggi", "High",
        "Ágreiningur eigenda og samningsaðila er vel rannsökt fyrirbæri. "
        "Tengsl við flækjustig (F1) eru sterk — fleiri aðilar = fleiri deilur."),
    "R29": RiskConfidence("Miðlungs öryggi", "Medium",
        "Ábyrgð á göllum eftir afhendingu er vel þekkt vandamál en umfang er breytilegt. "
        "Háð samningagerð og viðveru verktaka eftir framkvæmdir."),
    "R30": RiskConfidence("Miðlungs öryggi", "Medium",
        "Virðisaukning lands og millisala byggingarréttinda er vel þekkt vandamál á Íslandi. "
        "Líkindamat byggt á reynslu af lóðaúthlutun og sölu byggingarréttinda til lífeyrissjóða."),
    "R31": RiskConfidence("Miðlungs öryggi", "Medium",
        "Samhengisleysi milli áfanga er þekkt í stórum hverfisþróunarverkefnum. "
        "Háð verkefnastjórnun og áfangaskiptingu."),
    "R32": RiskConfidence("Miðlungs öryggi", "Medium",
        "Mannauðsskortur borgarinnar er raunverulegt vandamál en erfitt að mæla. "
        "Reykjavík hefur takmarkaða reynslu af svona stóru þróunarverkefni."),
    "R33": RiskConfidence("Miðlungs öryggi", "Medium",
        "Félagsleg blöndun sem nást ekki er vel þekkt vandamál á alþjóðavísu. "
        "Háð samningsskilmálum og framfylgdugetu borgar."),
    # v5 additions
    "R34": RiskConfidence("Hátt öryggi", "High",
        "Skattaleg flækja í samstarfsverkefnum sveitarfélaga og einkaaðila er vel skjalfest "
        "á Norðurlöndum og ESB. Líkindamat byggt á reynslu af PPP skattamálum."),
    "R35": RiskConfidence("Hátt öryggi", "High",
        "EES útboðsreglur eru lögbundnar og fyrirsjáanlegar. Áhrifin á tímalínu eru vel mæld "
        "í rannsóknum á opinberum framkvæmdum á Íslandi og Norðurlöndum."),
    "R36": RiskConfidence("Miðlungs öryggi", "Medium",
        "Slit á samstarfsverkefnum eru sjaldgæf en vel skjalfest þegar þau gerast. "
        "Kostnaðarmat byggt á dómsmálum og uppgjörum í PPP verkefnum."),
    "R37": RiskConfidence("Miðlungs öryggi", "Medium",
        "Hagsmunaárekstrar sveitarfélaga sem þróunaraðila eru þekkt vandamál í Evrópu. "
        "Líkindamat byggt á kærum til úrskurðarnefnda og dómstóla."),
}


# ═══════════════════════════════════════════════════════════════════
# 3. IMPROVED RISK CALCULATOR (Logistic)
# ═══════════════════════════════════════════════════════════════════

def calculate_risk_logistic(
    base_prob: float,
    factor_effects: List[float],
) -> Tuple[float, dict]:
    """
    Calculate scenario-adjusted risk probability using logistic transformation.
    
    Unlike the capped multiplicative model, this:
    - NEVER exceeds 100% or goes below 0%
    - Properly handles compounding risk factors
    - Maintains sensitivity across the full range
    
    Parameters:
    - base_prob: float (0, 1)
    - factor_effects: list of multipliers from calculate_factor_effect()
    
    Returns:
    - adjusted_probability: float (0, 1)
    - details: dict with intermediate steps
    """
    # Clamp base_prob to avoid log(0) or log(inf)
    base_prob = max(0.001, min(0.999, base_prob))
    
    # Step 1: Convert to log-odds
    base_log_odds = math.log(base_prob / (1 - base_prob))
    
    # Step 2: Each multiplier shifts log-odds by ln(multiplier)
    adjustments = []
    total_adjustment = 0.0
    for effect in factor_effects:
        effect = max(0.001, effect)  # Prevent log(0)
        adj = math.log(effect)
        adjustments.append(adj)
        total_adjustment += adj
    
    # Step 3: New log-odds
    adjusted_log_odds = base_log_odds + total_adjustment
    
    # Step 4: Convert back to probability via sigmoid
    # Protection against overflow: exp(710) exceeds float64 range
    if adjusted_log_odds > 700:
        adjusted_prob = 1.0 - 1e-15
    elif adjusted_log_odds < -700:
        adjusted_prob = 1e-15
    else:
        adjusted_prob = 1 / (1 + math.exp(-adjusted_log_odds))
    
    # Final clamp: sigmoid rounds to exactly 0.0/1.0 at |log-odds| > ~36
    adjusted_prob = max(1e-15, min(1 - 1e-15, adjusted_prob))
    
    return adjusted_prob, {
        "base_prob": base_prob,
        "base_log_odds": round(base_log_odds, 4),
        "adjustments": [round(a, 4) for a in adjustments],
        "total_adjustment": round(total_adjustment, 4),
        "adjusted_log_odds": round(adjusted_log_odds, 4),
        "final_prob": round(adjusted_prob, 4),
    }


# ═══════════════════════════════════════════════════════════════════
# 4. COMPREHENSIVE VALIDATION
# ═══════════════════════════════════════════════════════════════════

def validate_all():
    """Run all validations. Returns (passed, failed, warnings)."""
    
    from hallar_risk_factors.structural_factors import SCENARIO_FACTORS
    from hallar_risk_factors.risk_sensitivities import RISK_PROFILES
    from hallar_risk_factors.goal_impacts import GOALS, RISK_GOAL_IMPACTS
    from hallar_risk_factors.risk_calculator import (
        calculate_factor_effect, calculate_adjusted_probability,
    )
    
    passed = 0
    failed = 0
    warnings = 0
    
    print("=" * 70)
    print("VALIDATION REPORT")
    print("=" * 70)
    
    # 1. All scenarios have all factor justifications
    print("\n--- Justification Coverage ---")
    for sid in SCENARIO_FACTORS:
        if sid not in SCENARIO_FACTOR_JUSTIFICATIONS:
            print(f"  ❌ FAIL: {sid} missing from justifications")
            failed += 1
        else:
            for fid in ["F1", "F2", "F3", "F4", "F5", "F6", "F7"]:
                if fid not in SCENARIO_FACTOR_JUSTIFICATIONS[sid]:
                    print(f"  ❌ FAIL: {sid}.{fid} missing justification")
                    failed += 1
                else:
                    text = SCENARIO_FACTOR_JUSTIFICATIONS[sid][fid]
                    if len(text) < 50:
                        print(f"  ⚠️  WARN: {sid}.{fid} justification very short ({len(text)} chars)")
                        warnings += 1
                    else:
                        passed += 1
    
    # 2. All risks have confidence tiers
    print("\n--- Confidence Tier Coverage ---")
    for rid in RISK_PROFILES:
        if rid not in RISK_CONFIDENCE:
            print(f"  ❌ FAIL: {rid} missing confidence tier")
            failed += 1
        else:
            passed += 1
    
    # 3. Logistic model produces valid probabilities
    print("\n--- Logistic Model Bounds ---")
    for sid in SCENARIO_FACTORS:
        scenario = SCENARIO_FACTORS[sid]
        for rid, risk in RISK_PROFILES.items():
            effects = []
            for sens in risk.sensitivities:
                score = scenario.get_factor(sens.factor_id)
                effect = calculate_factor_effect(score, sens.direction, sens.sensitivity)
                effects.append(effect)
            
            for base_field in ["base_prob_low", "base_prob_likely", "base_prob_high"]:
                base = getattr(risk, base_field)
                prob, _ = calculate_risk_logistic(base, effects)
                
                if prob < 0 or prob > 1:
                    print(f"  ❌ FAIL: {sid}×{rid} ({base_field}): prob={prob}")
                    failed += 1
                elif prob > 0.99:
                    warnings += 1  # Very high but technically valid
                else:
                    passed += 1
    
    # 4. Factor ratings match justification claims
    print("\n--- Rating-Justification Consistency ---")
    for sid in SCENARIO_FACTORS:
        scenario = SCENARIO_FACTORS[sid]
        if sid not in SCENARIO_FACTOR_JUSTIFICATIONS:
            continue
        for fid in ["F1", "F2", "F3", "F4", "F5", "F6", "F7"]:
            value = scenario.get_factor(fid)
            text = SCENARIO_FACTOR_JUSTIFICATIONS[sid].get(fid, "")
            # Check that the justification mentions the actual score
            if f"Einkunn: {value}" not in text and f"einkunn {value}" not in text.lower():
                # Allow some flexibility but flag
                if str(value) not in text[:100]:
                    print(f"  ⚠️  WARN: {sid}.{fid}={value} — justification may not mention actual score")
                    warnings += 1
                else:
                    passed += 1
            else:
                passed += 1
    
    print(f"\n{'=' * 70}")
    print(f"RESULTS: {passed} passed, {failed} failed, {warnings} warnings")
    print(f"{'=' * 70}")
    
    return passed, failed, warnings


if __name__ == "__main__":
    validate_all()
